# Generated by Django 3.1.7 on 2021-02-21 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Intitulé')),
                ('date', models.DateField(verbose_name='Date')),
                ('number_max', models.IntegerField(verbose_name='Capacité maximum')),
                ('active', models.BooleanField(verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom et prénom')),
                ('mail', models.CharField(max_length=250, verbose_name='Adresse mail')),
                ('phone', models.CharField(max_length=10, verbose_name='Téléphone')),
                ('number', models.IntegerField(verbose_name='Nombre de personnes')),
                ('list_names', models.TextField(verbose_name='Prénom des personnes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='mainapp.event', verbose_name='Evénement')),
            ],
        ),
    ]
