# Generated by Django 3.1.7 on 2021-02-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='mail',
            new_name='email',
        ),
    ]
