# Generated by Django 3.1.7 on 2021-02-22 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210221_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Nombre de personnes'),
        ),
    ]
