# Generated by Django 3.1.7 on 2021-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210301_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_close',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Clôture'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_open',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ouverture'),
        ),
    ]
