# Generated by Django 3.1.7 on 2021-03-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210329_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_close',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_open',
        ),
    ]
